// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1
{
    public partial class Dosage
    {
        public long DosageId { get; set; }
        public long? UserId { get; set; }
        public string Name { get; set; }
        public int? Age { get; set; }
        public bool? Gender { get; set; }
        public string AadhaarNumber { get; set; }
        public string FatherName { get; set; }
        public string PhoneNo { get; set; }
        public DateTime? Dosage1Date { get; set; }
        public DateTime? Dosage2Date { get; set; }

        public virtual Register User { get; set; }
    }
}